DMS/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (password_reset, password_reset_done, password_reset_confirm,
                                       password_reset_complete)
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'DMS'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.FolderDetail, name='folder-details'),
    url(r'^(?P<folder_id>[0-9]+)/create_document/$', views.create_document, name='create_document'),
    url(r'^create_folder/$', views.create_folder, name='create-folder'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^doc/$', views.DocumentView, name='document'),
    url(r'^(?P<pk>[0-9]+)/versions/(?P<document_id>[0-9]+)/$', views.versions, name='versions'),
    url(r'^(?P<folder_id>[0-9]+)/delete_document/(?P<document_id>[0-9]+)/$', views.delete_document,
        name='delete_document'),
    url(r'^(?P<folder_id>[0-9]+)/check_in/(?P<document_id>[0-9]+)/$', views.checkin_document,
        name='checkin_document'),
    url(r'^(?P<id_folder>[0-9]+)/delete_folder/$', views.delete_folder, name='delete_folder'),

    url(r'^reset-password/$', password_reset,
        {'template_name': 'registration/password_reset_form.html', 'post_reset_redirect': 'DMS:password_reset_done',
         'email_template_name': 'registration/password_reset_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html',
         'post_reset_redirect': 'DMS:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name': 'registration/password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^test_view/(?P<pk>\d+)$', views.DocumentHistoryCompareView.as_view() ),
    # url(r'^document/add/$', views.DocumentCreate.as_view(), name='document-add'),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^?q=/', views.FolderDetail, name='folder-details'),

    # url(r'^folder/add/$', views.FolderCreate.as_view(), name='folder-add'),


]

urlpatterns = format_suffix_patterns(urlpatterns)

Licenta2017/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^DMS/', include('DMS.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DMS/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.template import loader
from django.utils.http import int_to_base36

from .models import Folder, Document, CustomUser


class DocumentForm(forms.ModelForm):
    EXTENSIONS = (('jpg', 'jpg'),
                  ('pdf', 'pdf'),
                  ('png', 'png'),
                  ('docx', 'docx'),
                  ('pptx', 'pptx'),
                  ('xlsx', 'xlsx'),
                  )

    type = forms.ChoiceField(choices=EXTENSIONS)
    class Meta:
        model = Document
        fields = ['name', 'owner', 'type', 'keywords', 'description', 'path']


class FolderForm(forms.ModelForm):
    CHOICES = [[x.name, x.name] for x in Folder.objects.all()]

    CHOICES.insert(0, ['root', "Root Folder"])
    root = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = Folder
        fields = ['name', 'root']


class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password']


class PassworResetForm(forms.Form):
    error_messages = {
        'unknown': ("That email address doesn't have an associated "
                    "user account. Are you sure you've registered?"),
        'unusable': ("The user account associated with this email "
                     "address cannot reset the password."),
    }

    def clean_email(self):
        """
        Validates that an active user exists with the given email address.
        """
        UserModel = get_user_model()
        email = self.cleaned_data["email"]
        self.users_cache = UserModel._default_manager.filter(email__iexact=email)
        if not len(self.users_cache):
            raise forms.ValidationError(self.error_messages['unknown'])
        if not any(user.is_active for user in self.users_cache):
            # none of the filtered users are active
            raise forms.ValidationError(self.error_messages['unknown'])
        return email

    def save(self, domain_override=None,
             subject_template_name='password_reset_subject.txt',
             email_template_name='password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        from django.core.mail import send_mail
        for user in self.users_cache:
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': int_to_base36(user.pk),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': use_https and 'https' or 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            send_mail(subject, email, from_email, [user.email])

DMS/views.py
from django.conf.urls import url
from django.contrib.auth import authenticate, login as auth_login, logout
# from django.contrib.auth.views import *
from django.core.mail import EmailMessage
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import FormView
from rest_framework import permissions
from rest_framework import viewsets
from reversion.models import Version
from reversion.views import RevisionMixin
from reversion_compare.views import HistoryCompareDetailView

from .forms import FolderForm, DocumentForm
from .models import Document, Folder, CustomUser
from .serializers import DocumentSerializer
from django.contrib.auth.models import Group


class DocumentHistoryCompareView(HistoryCompareDetailView):
    model = Document


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a CustomUser object is returned if it is.
        user = authenticate(email=email, password=password)
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:

                auth_login(request, user)
                return HttpResponseRedirect('/DMS/index/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your DMS account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(email, password))
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'DMS/login.html', {})


def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/DMS/login/')


def index(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/DMS/login/')
    else:
        user = request.user
        folder_name = Folder.objects.all()
        document_list = Document.objects.all()
        query = request.GET.get("q")
        if query:
            document_list = document_list.filter(Q(keywords__icontains=query) or
                                                 # Q(query in type)
                                                 Q(type__icontains=query) or
                                                 Q(name__contains=query) or
                                                 Q(owner__first_name=query)or
                                                 Q(creation_time__month=query)or
                                                    Q(creation_time__day=query)


                                                 ).distinct()
            return render(request, 'DMS/documents.html', {'document_list': document_list})
        context = {

            'folder_name': folder_name,
            'user': user
        }

        return render(request, 'DMS/index.html', context)


def FolderDetail(request, pk):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/DMS/login/')
    else:
        folder = get_object_or_404(Folder, pk=pk)
        folder_name = Folder.objects.all()
        # users_in_group = Group.objects.get(name="HR").user_set.all()
        document_list = Document.objects.filter(folder=folder)
        documents = []
        for doc in document_list:

            # Load a queryset of versions for a specific model instance.
            versions = Version.objects.get_for_object(doc)
            document_versions = []
            for version in versions:
                document_versions.append({
                    'date': version.revision.date_created,
                    'path': version.field_dict['path']

                })
            documents.append({
                'doc': doc,
                'versions': document_versions
            })
        query = request.GET.get("q")
        if query:
            document_list = document_list.filter(Q(keywords__icontains=query) |
                                                 # Q(query in type)|
                                                 Q(type__icontains=query) |
                                                 Q(name__contains=query) |
                                                 Q(owner__first_name=query)
                                                 ).distinct()
            return render(request, 'DMS/documents.html', {'document_list': document_list})

        context = {
            'folder': folder,
            'folder_name': folder_name,
            'documents': documents,
            # 'users_in_group':users_in_group
        }

        return render(request, "DMS/folder-details.html", context)


def DocumentView(request):
    document_list = Document.objects.all()
    query = request.GET.get("q")
    if query:
        document_list = document_list.filter(Q(keywords__icontains=query)
                                             # Q(type__icontains =query)|
                                             # Q(name__icontains=query)|
                                             # Q(owner__icontains=query)|
                                             # Q(description__icontains=query)
                                             ).distinct()
        return render(request, 'DMS/documents.html', {'document_list': document_list})

    return render(request, 'DMS/documents.html', {'document_list': document_list})


def versions(request, pk, document_id):
    folder = get_object_or_404(Folder, pk=pk)
    docs = get_object_or_404(Document, pk=document_id)
    document_list = Document.objects.filter(folder=folder)
    user =CustomUser.objects.all()
    documents = []
    for doc in document_list:

        # Load a queryset of versions for a specific model instance.
        versions = Version.objects.get_for_object(doc)
        document_versions = []
        for version in versions:
            document_versions.append({
                'date': version.revision.date_created,
                'path': version.field_dict['path'],
                'comment': version.revision.comment,
                'user_id': version.revision.user_id

            })
        documents.append({
            'doc': doc,
            'versions': document_versions
        })

    context = {
        'folder': folder,
        'documents': documents,
        'docs': docs,
        'user':user
    }
    return render(request, 'DMS/history.html', context)


def create_document(request, folder_id):
    # form = forms.DocumentForm()
    form = DocumentForm(request.POST or None, request.FILES or None)
    folder = get_object_or_404(Folder, pk=folder_id)
    # foldern = get_object_or_404(Folder,)
    folder_name = Folder.objects.all()
    if form.is_valid():
        folder_document = folder.document_set.all()
        for d in folder_document:
            if d.name == form.cleaned_data.get("name"):
                context = {
                    'folder': folder,
                    'form': form,
                    'folder_name': folder_name,
                    'error_message': 'You already added that document',
                }
                return render(request, 'DMS/folder-details.html', context)
        document = form.save(commit=False)
        document.folder = folder
        document.save()
        return HttpResponseRedirect('/DMS/' + folder_id)
    context = {
        'folder': folder,
        'form': form,
        'folder_name': folder_name
    }
    return render(request, 'DMS/create_document.html', context)


def checkin_document(request, folder_id, document_id):
    folder = get_object_or_404(Folder, pk=folder_id)
    documentid = Document.objects.get(pk=document_id)
    folder_name = Folder.objects.all()
    documents = Document.objects.all()
    if request.method == "POST":
        form = DocumentForm(request.POST, request.FILES, instance=documentid)
        if form.is_valid():
            document = form.save(commit=False)
            document.save()
            return HttpResponseRedirect('/DMS/' + folder_id)
        else:
            form = DocumentForm(initial={'name': documentid.name,
                                         'type': documentid.type,
                                         'owner': documentid.owner,
                                         'keywords': documentid.keywords,
                                         'description': documentid.description}, instance=documentid)
    context = {
        'folder': folder,
        'form': form,
        'folder_name': folder_name
    }
    return render(request, 'DMS/create_document.html', context)


def create_folder(request):
    form = FolderForm(request.POST or None, request.FILES or None)
    folder_name = Folder.objects.all()
    if form.is_valid():
        folder = form.save(commit=False)
        folder.save()

        return HttpResponseRedirect('/DMS/index')
    context = {
        "form": form,
        "folder_name": folder_name
    }

    return render(request, 'DMS/create_folder.html', context)


def delete_document(request, folder_id, document_id):
    folder = get_object_or_404(Folder, pk=folder_id)
    folder_name = Folder.objects.all()
    document = Document.objects.get(pk=document_id)
    document.delete()
    context = {
        "folder": folder,

DMS/templates/DMS/action_list_partial.html
{% load i18n l10n %}
{% if compare_view %}<form method="GET" action="{{ action }}">{% endif %}
<table id="change-history">
    <thead>
        <tr>
            {% if compare_view %}
                <th scope="col">
                    {% if comparable %}
                        <input type="submit" value="{% trans 'compare' %}">
                    {% else %}
                       <i>{% trans 'compare' %}</i>
                    {% endif %}
                </th>
            {% endif %}
            <th scope="col">{% trans 'Date/time' %}</th>
            <th scope="col">{% trans 'User' %}</th>
            <th scope="col">{% trans 'Comment' %}</th>
        </tr>
    </thead>
    <tbody>
        {% for action in action_list %}
            <tr>
                {% if compare_view %}
                <td scope="row">
                    {% if comparable %}
                       <input type="radio" name="version_id1" value="{{ action.version.pk|unlocalize }}" {% if action.first %}style="visibility:hidden" {% endif %}{% if version1.pk|unlocalize == action.version.pk|unlocalize or action.second %}checked="checked"{% endif%}/>
                       <input type="radio" name="version_id2" value="{{ action.version.pk|unlocalize }}" {% if version2.pk|unlocalize == action.version.pk|unlocalize or action.first == 1 %}checked="checked"{% endif%}/>
                    {% else %}
                       <i>-</i>
                    {% endif %}
                </td>
                {% endif %}
                <th scope="row">
                    {% if action.url %}
                        <a href="{{action.url}}">{{action.revision.date_created|date:_("DATETIME_FORMAT")}}</a>
                    {% else %}
                        {{action.revision.date_created|date:_("DATETIME_FORMAT")}}
                    {% endif %}
                </th>
                <td>
                    {% if action.revision.user %}
                        {{action.revision.user.username}}
                        {% if action.revision.user.first_name %} ({{action.revision.user.first_name}} {{action.revision.user.last_name}}){% endif %}
                    {% endif %}
                </td>
                <td>{{action.revision.comment|default:""}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% if compare_view %}</form>{% endif %}

DMS/templates/DMS/compare.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block extrastyle %}{{ block.super }}
<style type="text/css">
    /* minimal style for the diffs */
    del, ins {
        color: #000;
        text-decoration: none;
    }
    del { background-color: #ffe6e6; }
    ins { background-color: #e6ffe6; }
    sup.follow { color: #5555ff; }
</style>
{% endblock %}


{% block content %}
    <div id="content-main">

        {% block object-tools %}
            <ul class="object-tools">
              {% block object-tools-items %}
                {% include "reversion-compare/compare_links_partial.html" %}
              {% endblock %}
            </ul>
        {% endblock %}

        <p class="help">
            {% blocktrans with date1=version1.revision.date_created|date:_("DATETIME_FORMAT") date2=version2.revision.date_created|date:_("DATETIME_FORMAT") %}
                Compare <strong>{{ date1 }}</strong> with <strong>{{ date2 }}</strong>:
            {% endblocktrans %}
        </p>
        &lsaquo; <a href="{{history_url}}">{% trans "Go back to history list" %}</a>

        {% include "reversion-compare/compare_partial.html" %}

        &lsaquo; <a href="{{history_url}}">{% trans "Go back to history list" %}</a>
    </div>
{% endblock %}

DMS/templates/DMS/compare_DateTimeField.html
{% load i18n %}

<pre class="highlight">
<del>- {{ date1|date:_("DATETIME_FORMAT") }}</del> ({% trans 'time since that date:' %} {{ date1|timesince }})
<ins>+ {{ date2|date:_("DATETIME_FORMAT") }}</ins> ({% trans 'time since that date:' %} {{ date2|timesince }})
</pre>

DMS/templates/DMS/compare_generic_add.html
{% load i18n %}

<p class="highlight">
<i>{% trans "add:" %}</i> <ins>{{ value }}</ins>
</p>

DMS/templates/DMS/compare_generic_remove.html
{% load i18n %}

<p class="highlight">
<i>{% trans "remove:" %}</i> <del>{{ value }}</del>
</p>

DMS/templates/DMS/compare_links_partial.html
{% load i18n %}
{% if prev_url %}<li><a href="{{ prev_url }}">&lsaquo; {% trans "previous" %}</a></li>{% endif %}
{% if next_url %}<li><a href="{{ next_url }}">{% trans "next" %} &rsaquo;</a></li>{% endif %}

DMS/templates/DMS/compare_partial.html
{% load i18n %}
{% for field_diff in compare_data %}
    <h3>{% firstof field_diff.field.verbose_name field_diff.field.related_name %}{% if field_diff.is_related and not field_diff.follow %}<sup class="follow">*</sup>{% endif %}</h3>
    {% if field_diff.field.help_text %}<p class="help">{{ field_diff.field.help_text }}</p>{% endif %}
    <div class="module">
        <p>{{ field_diff.diff }}</p>
    </div>
{% empty %}
    <div class="module">
        <p><strong>{% trans "There are no differences." %}</strong></p>
    </div>
{% endfor %}

<h4>{% trans "Edit comment:" %}</h4>
<blockquote>{{ version2.revision.comment|default:"(no comment exists)" }}</blockquote>

{% if has_unfollowed_fields %}
<h4 class="follow">{% trans "Note:" %}</h4>
<p class="follow">
    {% blocktrans %}
        Fields/entries marked with <sup class="follow">*</sup> are not under reversion control.
        It may be that not all marked information are correct.
    {% endblocktrans %}
</p>
{% endif %}

DMS/templates/DMS/create_document.html
{% extends 'DMS/index.html' %}
{% block title %}Add a New Document{% endblock %}

{% block body %}

    <div class="col-sm-8 col-md-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Add a New Document</h3>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="folder" value="{{ folder }}">
                    {% include 'DMS/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

DMS/templates/DMS/create_folder.html
{% extends 'DMS/index.html' %}
{% block title %}Add a New Folder{% endblock %}

{% block content %}
    {% block body %}
        <div class="container-fluid">

            <div class="row">

                <div class="col-sm-12 col-md-7">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3>Add a New Folder</h3>
                            {% if error_message %}
                                <p><strong>{{ error_message }}</strong></p>
                            {% endif %}
                            <form class="form-horizontal" role="form" action="" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {% include 'DMS/form-template.html' %}
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">


                                        <button type="submit" class="btn btn-success">Submit
                                        </button>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endblock %}
{% endblock %}

DMS/templates/DMS/document_form.html
{% extends 'DMS/index.html' %}
{% block title %}Add a New Document{% endblock %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" acttion="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'DMS/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>

                                </div>

                            </div>

                        </form>
                    </div>

                </div>

            </div>

        </div>

    </div>
{% endblock %}

DMS/templates/DMS/folder_form.html
{% extends 'DMS/index.html' %}
{% block title %}Add a New Folder{% endblock %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" acttion="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'DMS/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>

                                </div>

                            </div>

                        </form>
                    </div>

                </div>

            </div>

        </div>

    </div>
{% endblock %}

DMS/templates/DMS/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} DMS {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'DMS/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet"
          href="http://www.orangehilldev.com/jstree-bootstrap-theme/demo/assets/dist/themes/proton/style.css"/>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jstree/3.0.9/themes/default/style.min.css"/>


    <script src="//cdnjs.cloudflare.com/ajax/libs/jstree/3.0.9/jstree.min.js"></script>


</head>


<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>

        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">

            <a href="http://127.0.0.1:8000/DMS/index" class="navbar-brand">Document management application</a>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">

                </div>
                <button type="submit" class="btn btn-default">Search</button>

            </form>


            <ul class="nav navbar-nav navbar-right">

                <li class="">
                    <a href="{% url 'DMS:create-folder' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Folder
                    </a>
                </li>
                <ul class="nav navbar-nav">
                    <li class="navbar-brand">
                        <span class="glyphicon glyphicon-user"> </span> {{ request.user.first_name }}
                    </li>

                </ul>
                <li class="">
                    <a href="{% url 'DMS:user_login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>


            </ul>


        </div>

    </div>

    </div>
</nav>

<!-- Left Folder Info -->
<div class="col-sm-4 col-md-3">

    <div class="panel panel-default">

        <div class="panel-body">

            <div id="myTree" class="using_events">
                <script>
                    $(function () {
                        $('.using_events')
                            .on('changed.jstree', function (e, data) {
                                var i, j, r = [], f;

                                for (i = 0, j = data.selected.length; i < j; i++) {
                                    r.push(data.instance.get_node([data.selected[i]]).text);
                                    var nm = r.toString();

                                    {% for f in folder_name %}
                                        if (nm === "{{ f.name }}")
                                            {#                                            console.log('Selected: ' + {{ f.id }});#}
                                            {#                                            window.location.href= "http://127.0.0.1:8000/DMS/" + {{ f.id }};#}
                                            window.location.href = "http://127.0.0.1:8000/DMS/" + {{ f.id }};

                                    {% endfor %}

                                }

                                {#                                console.log('Selected: ' + r);#}
                                {#                                window.location.href("http://127.0.0.1:8000/DMS/first" + r.join(', '));#}

                                {#									$('#event_result').html('Selected:<br /> ' + r.join(', '));#}
                            })
                            .jstree();
                    });
                </script>


            </div>


        </div>

    </div>

</div>


<script>
    {#{ "id" : "ajson1", "parent" : "#", "text" : "Simple root node" },#}
    $('#myTree')
    // create the instance
        .jstree({
            'core': {
                'data': [
                    {% for folder in folder_name %}

                        {
                            "id": "{{ folder.name }}", {% if folder.root == "root" %}"parent" : '#',
                            {% else %}"parent": "{{ folder.root }}",
                        {% endif %}
                            "text": "{{ folder.name }}"
                        },
                    {% endfor %}
                ]

            }
        });

</script>

{% block body %}
{% endblock %}

</body>
</html>